import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/gangguan_beranda_service.dart';
import '../theme/app_colors.dart';

class GangguanBerandaSection extends StatefulWidget{
  final Map<String,dynamic> sesi; const GangguanBerandaSection({super.key,required this.sesi});
  @override State<GangguanBerandaSection> createState()=>_GangguanBerandaSectionState();
}
class _GangguanBerandaSectionState extends State<GangguanBerandaSection>{
  late DateTime from,to; bool loading=true; String? error; List<Map<String,dynamic>> sets=[]; int active=0;
  @override void initState(){super.initState();final n=DateTime.now();from=DateTime(n.year,n.month,1);to=n;load();}
  String iso(DateTime d)=>DateFormat('yyyy-MM-dd').format(d);
  Future<void> load()async{setState((){loading=true;error=null;});try{final r=await GangguanBerandaService.load(token:'${widget.sesi['token']??''}',from:iso(from),to:iso(to),ulp:'${widget.sesi['ulp']??''}');if(!mounted)return;if(r['ok']!=true)throw Exception(r['message']??'Gagal memuat data');setState((){sets=List.from(r['datasets']??[]).map((e)=>Map<String,dynamic>.from(e as Map)).toList();loading=false;if(active>=sets.length)active=0;});}catch(e){if(mounted)setState((){loading=false;error='$e'.replaceFirst('Exception: ','');});}}
  Future<void> pick()async{final r=await showDateRangePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime.now().add(const Duration(days:1)),initialDateRange:DateTimeRange(start:from,end:to),helpText:'Rentang data gangguan');if(r!=null){from=r.start;to=r.end;load();}}
  @override Widget build(BuildContext c){return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Row(children:[const Expanded(child:Text('Data gangguan',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:AppColors.navy900))),OutlinedButton.icon(onPressed:pick,icon:const Icon(Icons.date_range_rounded,size:17),label:Text('${DateFormat('dd MMM').format(from)} - ${DateFormat('dd MMM').format(to)}'))]),
    const SizedBox(height:10),if(loading)const _ChartSkeleton() else if(error!=null)_state() else ...[_tabs(),const SizedBox(height:12),_chart()],
  ]);}
  Widget _tabs()=>SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:List.generate(sets.length,(i){final on=i==active;return Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(selected:on,label:Text('${sets[i]['title']} (${sets[i]['total']??0})'),onSelected:(_)=>setState(()=>active=i)));}))));
  Widget _chart(){final set=sets[active],pts=List<Map<String,dynamic>>.from((set['series']??[]).map((e)=>Map<String,dynamic>.from(e as Map))),max=pts.fold<int>(1,(m,e)=>(e['count']??0)>m?e['count']:m);if(pts.isEmpty)return const Padding(padding:EdgeInsets.symmetric(vertical:30),child:Center(child:Text('Tidak ada data pada rentang ini.')));return Container(height:220,padding:const EdgeInsets.fromLTRB(12,18,12,10),decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(18),border:Border.all(color:AppColors.neutral200)),child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:pts.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final p=pts[i],h=150*((p['count']??0)/max);return InkWell(onTap:()=>detail(set,'${p['date']}'),borderRadius:BorderRadius.circular(10),child:SizedBox(width:42,child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text('${p['count']}',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800)),const SizedBox(height:4),Container(height:h,width:24,decoration:BoxDecoration(color:[AppColors.brand600,AppColors.amber600,AppColors.success600][active],borderRadius:BorderRadius.circular(7))),const SizedBox(height:5),Text('${p['date']}'.substring(8),style:const TextStyle(fontSize:9,color:AppColors.neutral500))])));},));}
  void detail(Map<String,dynamic> set,String date){final rows=List<Map<String,dynamic>>.from((set['details']??[]).where((e)=>e['date']==date).map((e)=>Map<String,dynamic>.from(e as Map)));showModalBottomSheet(context:context,isScrollControlled:true,useSafeArea:true,builder:(ctx)=>DraggableScrollableSheet(expand:false,initialChildSize:.78,maxChildSize:.95,builder:(_,ctl)=>ListView(controller:ctl,padding:const EdgeInsets.all(20),children:[Text('${set['title']}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(DateFormat('dd MMMM yyyy','id_ID').format(DateTime.parse(date)),style:const TextStyle(color:AppColors.neutral500)),const SizedBox(height:16),...rows.map((r)=>_detailRow(r))])));}
  Widget _detailRow(Map<String,dynamic> r){final title='${r['Penyulang']??r['PENYULANG']??r['Penyulang_Fix']??'-'}',sub='${r['Nama PMT/OG/LBS/ACR']??r['Nama PMT/OG/ACR']??r['RECLOSER']??''}',skip={'date','Penyulang','PENYULANG','Penyulang_Fix','Nama PMT/OG/LBS/ACR','Nama PMT/OG/ACR','RECLOSER'};return ExpansionTile(tilePadding:EdgeInsets.zero,title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:sub.isEmpty?null:Text(sub),children:r.entries.where((e)=>!skip.contains(e.key)&&'${e.value}'.isNotEmpty).map((e)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:125,child:Text(e.key,style:const TextStyle(fontSize:11,color:AppColors.neutral500))),Expanded(child:Text('${e.value}',style:const TextStyle(fontSize:11,fontWeight:FontWeight.w600)))]))).toList());}
  Widget _state()=>Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:AppColors.red100,borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.cloud_off_rounded,color:AppColors.red600),const SizedBox(width:10),Expanded(child:Text(error!)),TextButton(onPressed:load,child:const Text('Coba lagi'))]));
}
class _ChartSkeleton extends StatelessWidget{const _ChartSkeleton();@override Widget build(BuildContext c)=>Container(height:220,decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(18),border:Border.all(color:AppColors.neutral200)),child:const Center(child:CircularProgressIndicator()));}
