import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:url_launcher/url_launcher.dart';
import '../db/app_database.dart';
import '../db/repositories/header_repository.dart';
import '../db/repositories/inspeksi_gardu_repository.dart';
import '../theme/app_colors.dart';

class LaporanHarianScreen extends StatefulWidget{
 final Map<String,dynamic>sesi;final String?targetSubTim,targetTim;
 const LaporanHarianScreen({super.key,required this.sesi,this.targetSubTim,this.targetTim});
 @override State<LaporanHarianScreen>createState()=>_State();
}
class _State extends State<LaporanHarianScreen>{
 final ins=InspeksiGarduRepository();List<dynamic>server=[];bool loading=true,offline=false;String?error;
 String get sub=>(widget.targetSubTim??widget.sesi['subTim']??widget.sesi['tim']??'ROW 01').toString();bool get isGardu=>sub.toLowerCase().contains('inspeksi gardu');
 String get today{final d=DateTime.now();return'${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}
 @override void initState(){super.initState();if(isGardu){ins.downloadListTemuan('${widget.sesi['token']??''}').catchError((_){ });setState(()=>loading=false);}else{loadServer();}}
 Future<void>loadServer()async{setState((){loading=true;error=null;});final r=await HeaderRepository().bacaLaporanHarian(token:'${widget.sesi['token']??''}',subTim:sub,tanggal:today);if(!mounted)return;setState((){loading=false;if(r['success']==true){server=r['data']??[];offline=r['offline']==true;}else error='${r['message']??'Gagal memuat'}';});}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(backgroundColor:AppColors.navy700,foregroundColor:Colors.white,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Laporan Harian',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text(sub,style:const TextStyle(fontSize:12,color:Colors.white70))]),actions:[IconButton(onPressed:isGardu?null:loadServer,icon:const Icon(Icons.refresh_rounded))]),body:isGardu?_localBody():_serverBody(),floatingActionButton:FloatingActionButton(backgroundColor:AppColors.navy700,onPressed:isGardu?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>_Form(sesi:widget.sesi))).then((_){if(mounted)setState((){});}):null,child:const Icon(Icons.add_rounded,color:Colors.white));
 Widget _localBody()=>StreamBuilder<List<InsGarduHeader>>(stream:ins.pantauLaporan(),builder:(context,s){final rows=s.data??[];if(rows.isEmpty)return const Center(child:Padding(padding:EdgeInsets.all(28),child:Text('Belum ada laporan hari ini. Tekan + untuk membuat laporan Inspeksi Gardu.',textAlign:TextAlign.center)));return ListView(padding:const EdgeInsets.all(16),children:[...rows.map((h)=>_localCard(h))]);});
 Widget _localCard(InsGarduHeader h)=>FutureBuilder<List<InsGarduRealisasi>>(future:ins.garduLaporan(h.localId),builder:(context,s){final gs=s.data??[];final done=gs.where((g)=>g.tier.isNotEmpty).length;return Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16),side:const BorderSide(color:Color(0xFFE2E8F0))),child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>_Detail(header:h,sesi:widget.sesi))),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(h.kodeHeader.isEmpty?'DRAFT ${h.localId.substring(h.localId.length-8)}':h.kodeHeader,style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.navy700))),_status(h.status)]),const SizedBox(height:10),Text('${h.hari}, ${h.tanggal}',style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:8),Row(children:[_mini('GARDU HARI INI','${gs.length}'),const SizedBox(width:28),_mini('SUDAH DIISI','$done'),const Spacer(),const Icon(Icons.chevron_right_rounded,color:Color(0xFF94A3B8))]),if(h.pesanGagal.isNotEmpty)...[const SizedBox(height:8),Text(h.pesanGagal,style:const TextStyle(fontSize:11,color:Colors.redAccent))]])))));});
 Widget _status(String x){final synced=x=='tersinkron',failed=x=='gagal';final c=synced?const Color(0xFF059669):failed?const Color(0xFFDC2626):const Color(0xFFB45309);return Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:c.withOpacity(.1),borderRadius:BorderRadius.circular(20)),child:Text(x.toUpperCase(),style:TextStyle(fontSize:9,fontWeight:FontWeight.w900,color:c)));}
 Widget _mini(String a,String b)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:9,color:Color(0xFF94A3B8),fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900,color:Color(0xFF334155)))]);
 Widget _serverBody(){if(loading)return const Center(child:CircularProgressIndicator());if(error!=null)return Center(child:Text(error!));if(server.isEmpty)return Center(child:Text('Belum ada laporan hari ini untuk $sub'));return ListView(padding:const EdgeInsets.all(16),children:[if(offline)const Text('Mode offline: data tersimpan di HP',style:TextStyle(color:Color(0xFFB45309))),...server.map((e)=>_serverCard(Map<String,dynamic>.from(e)))]);}
 Widget _serverCard(Map<String,dynamic>m)=>Card(elevation:0,child:ListTile(title:Text('${m['kodeHeader']??'-'}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${m['hari']??''}, ${m['tanggal']??''}\nKM ${m['kmAwal']??'-'} / ${m['kmAkhir']??'-'}'),isThreeLine:true,trailing:IconButton(icon:const Icon(Icons.send_rounded,color:Color(0xFF25D366)),onPressed:()=>_wa('${m['waText']??''}'))));
 Future<void>_wa(String t)async{if(t.trim().isEmpty)return;await launchUrl(Uri.parse('https://api.whatsapp.com/send?text=${Uri.encodeComponent(t)}'),mode:LaunchMode.externalApplication);}
}

class _Form extends StatefulWidget{final Map<String,dynamic>sesi;const _Form({required this.sesi});@override State<_Form>createState()=>_FormState();}
class _FormState extends State<_Form>{final repo=InspeksiGarduRepository(),awal=TextEditingController(),akhir=TextEditingController(),kmA=TextEditingController(),kmB=TextEditingController(),kendala=TextEditingController();bool saving=false;
 Future<void>gps(TextEditingController c)async{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();final x=await Geolocator.getCurrentPosition();c.text='${x.latitude.toStringAsFixed(6)}, ${x.longitude.toStringAsFixed(6)}';setState((){});}
 Future<void>save()async{if(awal.text.trim().isEmpty||akhir.text.trim().isEmpty)return;setState(()=>saving=true);final d=DateTime.now(),tanggal='${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}',hari=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][d.weekday%7];await repo.buatLaporan(ulp:'${widget.sesi['ulp']??''}',hari:hari,tanggal:tanggal,koordinatAwal:awal.text.trim(),koordinatAkhir:akhir.text.trim(),kmAwal:kmA.text.trim(),kmAkhir:kmB.text.trim(),kendala:kendala.text.trim(),inputBy:'${widget.sesi['username']??''}');if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(title:const Text('Tambah Laporan Harian'),subtitle: null),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Aktivitas Hari Ini',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:AppColors.navy700)),const SizedBox(height:20),_gps('Koordinat Gardu Awal',awal),_gps('Koordinat Gardu Akhir',akhir),Row(children:[Expanded(child:_field('KM Awal',kmA)),const SizedBox(width:10),Expanded(child:_field('KM Akhir',kmB))]),_field('Kendala',kendala,hint:'Kendala di Lapangan',lines:3)]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:SizedBox(height:50,child:ElevatedButton(onPressed:saving||awal.text.isEmpty||akhir.text.isEmpty?null:save,style:ElevatedButton.styleFrom(backgroundColor:AppColors.navy700,foregroundColor:Colors.white),child:Text(saving?'Menyimpan...':'Simpan Lokal',style:const TextStyle(fontWeight:FontWeight.w900)))))));
 Widget _gps(String l,TextEditingController c)=>Padding(padding:const EdgeInsets.only(bottom:14),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Expanded(child:_field(l,c)),const SizedBox(width:8),SizedBox(width:50,height:50,child:ElevatedButton(onPressed:()=>gps(c),style:ElevatedButton.styleFrom(padding:EdgeInsets.zero,backgroundColor:AppColors.navy700,foregroundColor:Colors.white),child:const Icon(Icons.my_location_rounded))) ]));
 Widget _field(String l,TextEditingController c,{String?hint,int lines=1})=>Padding(padding:const EdgeInsets.only(bottom:14),child:TextField(controller:c,maxLines:lines,onChanged:(_)=>setState((){}),decoration:InputDecoration(labelText:l,hintText:hint,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(13)))));
}

class _Detail extends StatelessWidget{final InsGarduHeader header;final Map<String,dynamic>sesi;const _Detail({required this.header,required this.sesi});
 @override Widget build(BuildContext context){final repo=InspeksiGarduRepository();return Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(title:const Text('Detail Laporan Harian')),body:FutureBuilder<List<InsGarduRealisasi>>(future:repo.garduLaporan(header.localId),builder:(context,s){final gs=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:[Card(elevation:0,child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[_r('Tanggal','${header.hari}, ${header.tanggal}'),_r('Koordinat Awal',header.koordinatAwal),_r('Koordinat Akhir',header.koordinatAkhir),_r('KM Awal / Akhir','${header.kmAwal} / ${header.kmAkhir}'),_r('Kendala',header.kendala)]))),const SizedBox(height:12),const Text('GARDU PENGUKURAN HARI INI',style:TextStyle(fontSize:11,letterSpacing:1,fontWeight:FontWeight.w900,color:Color(0xFF0284C7))),const SizedBox(height:8),...gs.map((g)=>_gCard(context,repo,g))]);}),);}
 Widget _r(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:125,child:Text(a,style:const TextStyle(color:Color(0xFF64748B)))),Expanded(child:Text(b.isEmpty?'-':b,style:const TextStyle(fontWeight:FontWeight.w800)))]));
 Widget _gCard(BuildContext context,InspeksiGarduRepository repo,InsGarduRealisasi g){final snap=Map<String,dynamic>.from(jsonDecode(g.snapshotJson));return Card(elevation:0,margin:const EdgeInsets.only(bottom:10),child:ListTile(contentPadding:const EdgeInsets.all(14),title:Text(g.nomorGardu,style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.navy700)),subtitle:Text('${snap['merkTrafo']??'-'} ${snap['dayaKva']??''} kVA\n${snap['alamat']??''}${g.tier.isEmpty?'':'\n${g.tier}'}'),isThreeLine:true,trailing:Icon(g.tier.isEmpty?Icons.add_circle_outline:Icons.check_circle,color:g.tier.isEmpty?const Color(0xFF0284C7):const Color(0xFF059669)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>_TemuanEditor(g:g))).then((_){(context as Element).markNeedsBuild();})));}
}

class _TemuanEditor extends StatefulWidget{final InsGarduRealisasi g;const _TemuanEditor({required this.g});@override State<_TemuanEditor>createState()=>_TemuanEditorState();}
class _TemuanEditorState extends State<_TemuanEditor>{final repo=InspeksiGarduRepository(),picker=ImagePicker();String tier='Tier 1';List<ListTemuan> options=[];final Map<String,Map<String,String>> selected={};
 @override void initState(){super.initState();tier=widget.g.tier.isEmpty?'Tier 1':widget.g.tier;load();}
 Future<void>load()async{options=await repo.pilihan(tier);if(mounted)setState((){});}
 Future<void>photo(String name,String key)async{final x=await picker.pickImage(source:ImageSource.camera,imageQuality:75,maxWidth:1600);if(x!=null)setState(()=>(selected[name]??={})[key]=x.path);}
 Future<void>save()async{for(final e in selected.entries){if((e.value['fotoTemuanPath']??'').isEmpty||(e.value['fotoGarduPath']??'').isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Lengkapi 2 foto untuk ${e.key}')));return;}}final rows=selected.entries.map((e)=>{'tier':options.firstWhere((x)=>x.temuan==e.key).tier,'temuan':e.key,...e.value}).toList();await repo.setGardu(gardu:widget.g,tier:tier,temuan:rows);if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.g.nomorGardu),actions:[TextButton(onPressed:save,child:const Text('SIMPAN'))]),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:DropdownButtonFormField<String>(value:tier,items:['Tier 1','Tier 2','Tier 1 & Tier 2'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){tier=v!;selected.clear();load();},decoration:const InputDecoration(labelText:'Inspeksi Tier',border:OutlineInputBorder()))),Expanded(child:ListView.builder(itemCount:options.length,itemBuilder:(context,i){final o=options[i],on=selected.containsKey(o.temuan);return Card(elevation:0,margin:const EdgeInsets.fromLTRB(16,0,16,9),child:Column(children:[CheckboxListTile(value:on,title:Text(o.temuan),subtitle:Text(o.tier),onChanged:(v)=>setState((){if(v==true)selected[o.temuan]={};else selected.remove(o.temuan);})),if(on)Padding(padding:const EdgeInsets.fromLTRB(12,0,12,12),child:Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>photo(o.temuan,'fotoTemuanPath'),icon:Icon((selected[o.temuan]?['fotoTemuanPath']??'').isEmpty?Icons.camera_alt_outlined:Icons.check_circle,color:(selected[o.temuan]?['fotoTemuanPath']??'').isEmpty?null:Colors.green),label:const Text('Foto Temuan'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>photo(o.temuan,'fotoGarduPath'),icon:Icon((selected[o.temuan]?['fotoGarduPath']??'').isEmpty?Icons.home_work_outlined:Icons.check_circle,color:(selected[o.temuan]?['fotoGarduPath']??'').isEmpty?null:Colors.green),label:const Text('Foto Gardu')))]))]));}))]));
}
