import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import '../db/app_database.dart';
import '../db/repositories/inspeksi_gardu_repository.dart';
import '../theme/app_colors.dart';
import 'inspeksi_jaringan_screen.dart';

class LaporanHarianScreen extends StatefulWidget{
 final Map<String,dynamic>sesi;final String?targetSubTim,targetTim;
 const LaporanHarianScreen({super.key,required this.sesi,this.targetSubTim,this.targetTim});
 @override State<LaporanHarianScreen>createState()=>_LaporanState();
}
class _LaporanState extends State<LaporanHarianScreen>{
 final repo=InspeksiGarduRepository();
 String get sub=>(widget.targetSubTim??widget.sesi['subTim']??widget.sesi['tim']??'ROW 01').toString();bool get gardu=>sub.toLowerCase().contains('inspeksi gardu');
 @override void initState(){super.initState();if(gardu){repo.downloadListTemuan('${widget.sesi['token']??''}').catchError((_){ });}}
 @override Widget build(BuildContext context){if(!gardu)return InspeksiJaringanScreen(sesi:widget.sesi);return Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(backgroundColor:AppColors.navy700,foregroundColor:Colors.white,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Laporan Harian',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text(sub,style:const TextStyle(fontSize:12,color:Colors.white70))])),body:_local(),floatingActionButton:FloatingActionButton(backgroundColor:AppColors.navy700,onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>InsGarduForm(sesi:widget.sesi))),child:const Icon(Icons.add_rounded,color:Colors.white)));}
 Widget _local()=>StreamBuilder<List<InsGarduHeader>>(stream:repo.pantauLaporan(),builder:(context,s){final list=s.data??[];if(list.isEmpty)return const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('Belum ada laporan. Tekan + untuk membuat Laporan Harian Inspeksi Gardu.',textAlign:TextAlign.center)));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_draft(list[i]));});
 Widget _draft(InsGarduHeader h)=>FutureBuilder<List<InsGarduRealisasi>>(future:repo.garduLaporan(h.localId),builder:(context,s){final gs=s.data??[],done=gs.where((x)=>x.tier.isNotEmpty).length;return Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16),side:const BorderSide(color:Color(0xFFE2E8F0))),child:ListTile(contentPadding:const EdgeInsets.all(16),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>InsGarduDetail(header:h))),title:Text(h.kodeHeader.isEmpty?'Draft Lokal':h.kodeHeader,style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.navy700)),subtitle:Text('${h.hari}, ${h.tanggal}\n$done dari ${gs.length} gardu sudah diisi'),isThreeLine:true,trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[_badge(h.status),const Icon(Icons.chevron_right_rounded)])));});
 Widget _badge(String x){final c=x=='tersinkron'?Colors.green:x=='gagal'?Colors.red:Colors.orange;return Text(x.toUpperCase(),style:TextStyle(fontSize:9,fontWeight:FontWeight.w900,color:c));}
}

class InsGarduForm extends StatefulWidget{final Map<String,dynamic>sesi;const InsGarduForm({super.key,required this.sesi});@override State<InsGarduForm>createState()=>_FormState();}
class _FormState extends State<InsGarduForm>{final repo=InspeksiGarduRepository(),a=TextEditingController(),b=TextEditingController(),ka=TextEditingController(),kb=TextEditingController(),kendala=TextEditingController();bool busy=false;
 Future<void>_gps(TextEditingController c)async{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();final x=await Geolocator.getCurrentPosition();c.text='${x.latitude.toStringAsFixed(6)}, ${x.longitude.toStringAsFixed(6)}';setState((){});}
 Future<void>_save()async{if(a.text.trim().isEmpty||b.text.trim().isEmpty)return;setState(()=>busy=true);final d=DateTime.now(),tgl='${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}',hari=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][d.weekday%7];await repo.buatLaporan(ulp:'${widget.sesi['ulp']??''}',hari:hari,tanggal:tgl,koordinatAwal:a.text.trim(),koordinatAkhir:b.text.trim(),kmAwal:ka.text.trim(),kmAkhir:kb.text.trim(),kendala:kendala.text.trim(),inputBy:'${widget.sesi['username']??''}');if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(title:const Text('Tambah Laporan Harian')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Aktivitas Hari Ini',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:AppColors.navy700)),const SizedBox(height:20),_gpsField('Koordinat Gardu Awal',a),_gpsField('Koordinat Gardu Akhir',b),Row(children:[Expanded(child:_field('KM Awal',ka)),const SizedBox(width:10),Expanded(child:_field('KM Akhir',kb))]),_field('Kendala',kendala,hint:'Kendala di Lapangan',lines:3)]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:SizedBox(height:50,child:ElevatedButton(onPressed:busy||a.text.isEmpty||b.text.isEmpty?null:_save,style:ElevatedButton.styleFrom(backgroundColor:AppColors.navy700,foregroundColor:Colors.white),child:Text(busy?'Menyimpan...':'Simpan Lokal',style:const TextStyle(fontWeight:FontWeight.w900)))))));
 Widget _gpsField(String l,TextEditingController c)=>Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:_field(l,c)),const SizedBox(width:8),Padding(padding:const EdgeInsets.only(top:4),child:SizedBox(width:50,height:50,child:ElevatedButton(onPressed:()=>_gps(c),style:ElevatedButton.styleFrom(padding:EdgeInsets.zero,backgroundColor:AppColors.navy700,foregroundColor:Colors.white),child:const Icon(Icons.my_location_rounded))))]);
 Widget _field(String l,TextEditingController c,{String?hint,int lines=1})=>Padding(padding:const EdgeInsets.only(bottom:14),child:TextField(controller:c,maxLines:lines,onChanged:(_)=>setState((){}),decoration:InputDecoration(labelText:l,hintText:hint,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(13)))));
}

class InsGarduDetail extends StatefulWidget{final InsGarduHeader header;const InsGarduDetail({super.key,required this.header});@override State<InsGarduDetail>createState()=>_DetailState();}
class _DetailState extends State<InsGarduDetail>{final repo=InspeksiGarduRepository();@override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF6F8FC),appBar:AppBar(title:const Text('Detail Laporan Harian')),body:FutureBuilder<List<InsGarduRealisasi>>(future:repo.garduLaporan(widget.header.localId),builder:(context,s){final gs=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:[Card(elevation:0,child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[_row('Tanggal','${widget.header.hari}, ${widget.header.tanggal}'),_row('Koordinat Awal',widget.header.koordinatAwal),_row('Koordinat Akhir',widget.header.koordinatAkhir),_row('KM Awal / Akhir','${widget.header.kmAwal} / ${widget.header.kmAkhir}'),_row('Kendala',widget.header.kendala)]))),const SizedBox(height:12),const Text('GARDU PENGUKURAN HARI INI',style:TextStyle(fontSize:11,letterSpacing:1,fontWeight:FontWeight.w900,color:Color(0xFF0284C7))),const SizedBox(height:8),...gs.map((g)=>_card(g))]);}));
 Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:125,child:Text(a,style:const TextStyle(color:Color(0xFF64748B)))),Expanded(child:Text(b.isEmpty?'-':b,style:const TextStyle(fontWeight:FontWeight.w800)))]));
 Widget _card(InsGarduRealisasi g){final m=Map<String,dynamic>.from(jsonDecode(g.snapshotJson));return Card(elevation:0,margin:const EdgeInsets.only(bottom:9),child:ListTile(contentPadding:const EdgeInsets.all(14),title:Text(g.nomorGardu,style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.navy700)),subtitle:Text('${m['merkTrafo']??'-'} ${m['dayaKva']??''} kVA\n${m['alamat']??''}${g.tier.isEmpty?'':'\n${g.tier}'}'),isThreeLine:true,trailing:Icon(g.tier.isEmpty?Icons.add_circle_outline:Icons.check_circle,color:g.tier.isEmpty?Colors.blue:Colors.green),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>InsGarduTemuanEditor(g:g))).then((_){if(mounted)setState((){});})));}
}

class InsGarduTemuanEditor extends StatefulWidget{final InsGarduRealisasi g;const InsGarduTemuanEditor({super.key,required this.g});@override State<InsGarduTemuanEditor>createState()=>_TemuanState();}
class _TemuanState extends State<InsGarduTemuanEditor>{final repo=InspeksiGarduRepository(),picker=ImagePicker();String tier='Tier 1';List<ListTemuan> options=[];final Map<String,Map<String,String>>selected={};
 @override void initState(){super.initState();tier=widget.g.tier.isEmpty?'Tier 1':widget.g.tier;_load();}
 Future<void>_load()async{options=await repo.pilihan(tier);if(mounted)setState((){});}
 Future<void>_photo(String name,String key)async{final x=await picker.pickImage(source:ImageSource.camera,imageQuality:75,maxWidth:1600);if(x!=null)setState(()=>(selected[name]??={})[key]=x.path);}
 Future<void>_save()async{for(final e in selected.entries){if((e.value['fotoTemuanPath']??'').isEmpty||(e.value['fotoGarduPath']??'').isEmpty){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Lengkapi 2 foto untuk ${e.key}')));return;}}final rows=selected.entries.map((e)=>{'tier':options.firstWhere((x)=>x.temuan==e.key).tier,'temuan':e.key,...e.value}).toList();await repo.setGardu(gardu:widget.g,tier:tier,temuan:rows);if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.g.nomorGardu),actions:[TextButton(onPressed:_save,child:const Text('SIMPAN'))]),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:DropdownButtonFormField<String>(value:tier,items:['Tier 1','Tier 2','Tier 1 & Tier 2'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){tier=v!;selected.clear();_load();},decoration:const InputDecoration(labelText:'Inspeksi Tier',border:OutlineInputBorder()))),Expanded(child:ListView.builder(itemCount:options.length,itemBuilder:(context,i){final o=options[i],on=selected.containsKey(o.temuan),x=selected[o.temuan]??{};return Card(elevation:0,margin:const EdgeInsets.fromLTRB(16,0,16,9),child:Column(children:[CheckboxListTile(value:on,title:Text(o.temuan),subtitle:Text(o.tier),onChanged:(v)=>setState((){if(v==true)selected[o.temuan]={};else selected.remove(o.temuan);}),),if(on)Padding(padding:const EdgeInsets.fromLTRB(12,0,12,12),child:Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>_photo(o.temuan,'fotoTemuanPath'),icon:Icon(x['fotoTemuanPath']==null?Icons.camera_alt_outlined:Icons.check_circle,color:x['fotoTemuanPath']==null?null:Colors.green),label:const Text('Foto Temuan'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>_photo(o.temuan,'fotoGarduPath'),icon:Icon(x['fotoGarduPath']==null?Icons.home_work_outlined:Icons.check_circle,color:x['fotoGarduPath']==null?null:Colors.green),label:const Text('Foto Gardu')))]))]));}))]));
}
