import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:url_launcher/url_launcher.dart';

import '../db/repositories/temuan_map_repository.dart';
import '../theme/app_colors.dart';

class PetaTemuanScreen extends StatefulWidget{final Map<String,dynamic>sesi;final VoidCallback?onBack;const PetaTemuanScreen({super.key,required this.sesi,this.onBack});@override State<PetaTemuanScreen>createState()=>_State();}
class _State extends State<PetaTemuanScreen>{
 final repository=TemuanMapRepository(),map=MapController(),search=TextEditingController();List<TemuanMapPoint>points=const[];bool loading=true,forwarding=false;String?error;String query='',status='Semua status',tier='Semua tier';TemuanMapPoint?selected;double zoom=11.5;
 String get token=>'${widget.sesi['token']??''}',ulp=>'${widget.sesi['ulp']??''}';bool get allUlp=>'${widget.sesi['role']??''}'.toLowerCase().replaceAll(' ','')=='superuser';
 @override void initState(){super.initState();load();}@override void dispose(){search.dispose();super.dispose();}
 Future<void>load()async{setState((){loading=true;error=null;});try{final rows=await repository.load(ulp:ulp,allUlp:allUlp);if(!mounted)return;setState((){points=rows;loading=false;if(selected!=null&&!rows.any((p)=>p.kode==selected!.kode))selected=null;});if(rows.isNotEmpty)WidgetsBinding.instance.addPostFrameCallback((_){if(mounted)map.move(center(rows),12.2);});}catch(e){if(mounted)setState((){loading=false;error='$e';});}}
 LatLng center(List<TemuanMapPoint>r)=>LatLng(r.fold<double>(0,(s,p)=>s+p.latitude)/r.length,r.fold<double>(0,(s,p)=>s+p.longitude)/r.length);
 String statusLabel(String s){final v=s.toLowerCase();if(v.contains('selesai'))return'Selesai';if(v.contains('progress'))return'Dalam proses';return'Belum ditugaskan';}
 Color color(String s)=>statusLabel(s)=='Selesai'?AppColors.success700:statusLabel(s)=='Dalam proses'?AppColors.amber700:AppColors.red600;
 List<TemuanMapPoint>get filtered=>points.where((p){final h='${p.kode} ${p.temuan} ${p.penyulang} ${p.section} ${p.nomorTiang} ${p.tim}'.toLowerCase();return(query.isEmpty||h.contains(query.toLowerCase()))&&(status=='Semua status'||status==statusLabel(p.status))&&(tier=='Semua tier'||tier==p.tier);}).toList();
 double get markerSize=>(14+(zoom-7)*2.6).clamp(15,38).toDouble();
 Future<void>navigate(TemuanMapPoint p)async{final uri=Uri.parse('https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}');if(!await launchUrl(uri,mode:LaunchMode.externalApplication)&&mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Google Maps tidak dapat dibuka.')));}
 Future<void>forward(TemuanMapPoint p)async{setState(()=>forwarding=true);try{final teams=await repository.teams(token:token,ulp:ulp);if(!mounted)return;final team=await showModalBottomSheet<String>(context:context,showDragHandle:true,builder:(ctx)=>SafeArea(child:ListView(shrinkWrap:true,padding:const EdgeInsets.fromLTRB(16,0,16,18),children:[const Text('Pilih tim tujuan',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),if(teams.isEmpty)const ListTile(title:Text('Belum ada tim tersedia'))else for(final t in teams)ListTile(leading:const Icon(Icons.groups_outlined),title:Text(t),onTap:()=>Navigator.pop(ctx,t))])));if(team==null)return;final message=await repository.forward(token:token,code:p.kode,team:team);if(!mounted)return;setState(()=>selected=null);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(message),backgroundColor:AppColors.success700));await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'.replaceFirst('Exception: ','')),backgroundColor:AppColors.red600));}finally{if(mounted)setState(()=>forwarding=false);}}
 @override Widget build(BuildContext context){final rows=filtered;return Scaffold(backgroundColor:const Color(0xFFF5F8FC),appBar:AppBar(backgroundColor:AppColors.navy700,foregroundColor:Colors.white,leading:widget.onBack==null?null:IconButton(onPressed:widget.onBack,icon:const Icon(Icons.arrow_back_rounded)),title:const Text('Peta Temuan',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:loading?null:load,icon:const Icon(Icons.refresh_rounded))]),body:RefreshIndicator(onRefresh:load,child:CustomScrollView(physics:const AlwaysScrollableScrollPhysics(),slivers:[SliverToBoxAdapter(child:toolbar()),SliverFillRemaining(child:Stack(children:[FlutterMap(mapController:map,options:MapOptions(initialCenter:const LatLng(-3.01,106.45),initialZoom:11.5,onPositionChanged:(camera,_){if((camera.zoom-zoom).abs()>.15&&mounted)setState(()=>zoom=camera.zoom);}),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'id.co.ulptoboali.sisi'),MarkerLayer(markers:[for(final p in rows)Marker(point:LatLng(p.latitude,p.longitude),width:44,height:46,child:GestureDetector(onTap:(){setState(()=>selected=p);map.move(LatLng(p.latitude,p.longitude),16);},child:Center(child:Icon(Icons.location_on_outlined,size:selected?.kode==p.kode?markerSize+7:markerSize,color:color(p.status).withValues(alpha:zoom<9?.62:.92),shadows:zoom<10?null:const[Shadow(color:Colors.black26,blurRadius:3)]))))]),SimpleAttributionWidget(source:const Text('© OpenStreetMap contributors'),onTap:()=>launchUrl(Uri.parse('https://www.openstreetmap.org/copyright')))]),Positioned(top:12,left:12,child:counter(rows.length)),if(loading)const Center(child:CircularProgressIndicator()),if(error!=null)Center(child:message('Peta belum dapat dimuat',error!)),if(!loading&&error==null&&points.isEmpty)Center(child:message('Belum ada titik temuan','Download modul Inspeksi pada Data Master terlebih dahulu.')),if(selected!=null)Align(alignment:Alignment.bottomCenter,child:detail(selected!))]))])));}
 Widget toolbar(){final tiers=points.map((p)=>p.tier).where((v)=>v.isNotEmpty).toSet().toList()..sort();return Material(color:Colors.white,child:Padding(padding:const EdgeInsets.fromLTRB(14,12,14,10),child:Column(children:[TextField(controller:search,onChanged:(v)=>setState(()=>query=v),decoration:InputDecoration(hintText:'Cari penyulang, tiang, atau temuan',prefixIcon:const Icon(Icons.search_rounded),isDense:true,filled:true,fillColor:const Color(0xFFF5F8FC),border:OutlineInputBorder(borderRadius:BorderRadius.circular(13),borderSide:BorderSide.none))),const SizedBox(height:9),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[popup(status,const['Semua status','Belum ditugaskan','Dalam proses','Selesai'],(v)=>status=v),const SizedBox(width:7),popup(tier,['Semua tier',...tiers],(v)=>tier=v),const SizedBox(width:7),const Chip(avatar:Icon(Icons.layers_outlined,size:17),label:Text('Aktif + Arsip'))]))])));}
 Widget popup(String value,List<String>values,ValueChanged<String>change)=>PopupMenuButton<String>(onSelected:(v)=>setState(()=>change(v)),itemBuilder:(_)=>values.map((v)=>PopupMenuItem(value:v,child:Text(v))).toList(),child:Chip(label:Text(value),avatar:const Icon(Icons.expand_more_rounded,size:17)));
 Widget counter(int n)=>Container(padding:const EdgeInsets.symmetric(horizontal:11,vertical:8),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),boxShadow:const[BoxShadow(color:Colors.black12,blurRadius:10)]),child:Text('$n temuan terpetakan',style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800)));
 Widget detail(TemuanMapPoint p)=>SafeArea(minimum:const EdgeInsets.all(10),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(19),boxShadow:const[BoxShadow(color:Colors.black26,blurRadius:22)]),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:color(p.status).withValues(alpha:.12),borderRadius:BorderRadius.circular(12)),alignment:Alignment.center,child:Text(p.tier.isEmpty?'T':p.tier.replaceAll('Tier ','T'),style:TextStyle(fontWeight:FontWeight.w900,color:color(p.status)))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.temuan.isEmpty?'Temuan inspeksi':p.temuan,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)),Text(p.kode,style:const TextStyle(fontSize:11,color:AppColors.neutral500))])),IconButton(onPressed:()=>setState(()=>selected=null),icon:const Icon(Icons.close_rounded))]),const SizedBox(height:10),Text('${p.penyulang} · ${p.section}\n${p.nomorTiang.isEmpty?p.objek:p.nomorTiang}',style:const TextStyle(height:1.4)),const SizedBox(height:10),Row(children:[Icon(Icons.circle,size:9,color:color(p.status)),const SizedBox(width:6),Text(statusLabel(p.status),style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700)),const Spacer(),Text(p.tanggal,style:const TextStyle(fontSize:11,color:AppColors.neutral500))]),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>navigate(p),icon:const Icon(Icons.directions_outlined),label:const Text('Google Maps'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:forwarding?null:()=>forward(p),icon:forwarding?const SizedBox.square(dimension:16,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.forward_to_inbox_outlined),label:const Text('Teruskan tim')))])])));
 Widget message(String title,String body)=>Container(margin:const EdgeInsets.all(24),padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.map_outlined,size:40,color:AppColors.navy700),const SizedBox(height:10),Text(title,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(body,textAlign:TextAlign.center)]));
}
