'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const root=path.join(__dirname,'..','SiSi_BackEnd','Core');
const source=fs.readFileSync(path.join(root,'ZZZZZZ-BA-Final-Upload-Auth.js'),'utf8');
const helper=fs.readFileSync(path.join(root,'ZZZZZZZZZZZZ-Stage4-Sheet-Write-Safety.js'),'utf8');
const TOKEN='11111111-1111-4111-8111-111111111111';
function harness({session}={}){const calls=[];const context={uploadBaFinal(request){calls.push(request);return{ok:true,idBA:request.idBA,url:'drive-url'};},getPageContent:(token,page)=>({success:true,html:'<main>',sesi:{token},page}),guard_(args,opts){const request=args&&args[0]||{},token=String(request.token||'');if(token!==TOKEN)throw new Error(token?'Sesi habis atau tidak valid.':'Sesi tidak ditemukan.');if(!session)throw new Error('Sesi habis atau tidak valid.');if(!String(session.ulp||'').trim())throw new Error('Akun belum terhubung ke ULP.');return{token,sesi:session,ulp:session.ulp,opts};}};vm.createContext(context);vm.runInContext(helper,context);vm.runInContext(source,context);return{context,calls};}
test('anonymous upload is rejected before Drive or sheet work',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.uploadBaFinal({idBA:'BA-1',dataUrl:'data:application/pdf;base64,AA=='}),/Sesi tidak/);assert.equal(h.calls.length,0);});
test('invalid session is rejected before side effects',()=>{const h=harness();assert.throws(()=>h.context.uploadBaFinal({token:TOKEN,idBA:'BA-1'}),/Sesi habis/);assert.equal(h.calls.length,0);});
test('blank session ULP is rejected before side effects',()=>{const h=harness({session:{ulp:''}});assert.throws(()=>h.context.uploadBaFinal({token:TOKEN,idBA:'BA-1'}),/ULP/);assert.equal(h.calls.length,0);});
test('valid upload strips token and sanitizes formula-like filename and URL',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.uploadBaFinal({token:TOKEN,idBA:'BA-1',peralatan:'Gardu',fileName:'=HYPERLINK("x")',url:'@formula'});assert.equal(r.ok,true);assert.equal(r.idBA,'BA-1');assert.equal(h.calls.length,1);assert.equal(h.calls[0].idBA,'BA-1');assert.equal(h.calls[0].peralatan,'Gardu');assert.equal(h.calls[0].fileName,"'=HYPERLINK(\"x\")");assert.equal(h.calls[0].url,"'@formula");assert.equal(Object.prototype.hasOwnProperty.call(h.calls[0],'token'),false);});
test('BA page registers final upload for token injection',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'SIE-BeritaAcara');assert.match(r.html,/uploadBaFinal/);assert.match(r.html,/SISI_BUTUH_TOKEN/);});
test('unrelated pages are not modified',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'Dashboard');assert.equal(r.html,'<main>');});
