'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','SiSi_BackEnd','Core','ZZZZ-BA-List-Auth.js'),'utf8');
function harness({session,switchingError,rows,switchingRows}={}){const counts={original:0,switching:0,sheets:0,helpers:0};let context;const original=filter=>{counts.original++;counts.sheets++;let merged=(rows||[]).slice();if(String(filter.peralatan||'').toLowerCase()!=='gardu'){try{const sw=context.getDataSwitching({});if(sw&&sw.ok)merged=merged.concat(sw.rows||[]);}catch(error){return{ok:false,message:'Error Berita Acara: '+error.message};}}merged.sort((a,b)=>String(b.tanggal||'').localeCompare(String(a.tanggal||'')));const status=String(filter.statusBA||'').toLowerCase();if(status)merged=merged.filter(r=>(r.baTtd?'selesai ttd':r.filePdfUrl?'proses ttd':'draft ba')===status);return{ok:true,rows:merged,total:merged.length};};context={getDataBeritaAcara:original,getPageContent:(token,page)=>({success:true,html:'<main>',sesi:{token}}),getDataSwitching(){counts.switching++;if(switchingError)throw new Error(switchingError);return{ok:true,rows:switchingRows||[]};},guard_(args){counts.helpers++;const f=args&&args[0],token=f&&f.token;if(token!=='valid-token')throw new Error(token?'Sesi habis atau tidak valid.':'Sesi tidak ditemukan.');if(!session)throw new Error('Sesi habis atau tidak valid.');if(!String(session.ulp||'').trim())throw new Error('Akun belum terhubung ke ULP.');return{sesi:session,ulp:session.ulp,token};},_guardErrorAkses_:e=>/Sesi|Akses ditolak|ULP|bukan milik/i.test(String(e&&e.message))};vm.createContext(context);vm.runInContext(source,context);return{context,counts};}
const gardu=[{idBA:'G1',tanggal:'2026-03-02',baTtd:'',filePdfUrl:'pdf'},{idBA:'G2',tanggal:'2026-03-01',baTtd:'signed',filePdfUrl:'pdf'}],switching=[{idBA:'S1',tanggal:'2026-03-03',baTtd:'',filePdfUrl:''}];
test('no token rejected before reads',()=>{const h=harness({session:{ulp:'ULP Toboali'},rows:gardu});assert.throws(()=>h.context.getDataBeritaAcara({}),/Sesi tidak/);assert.equal(h.counts.original,0);});
test('invalid token rejected',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.getDataBeritaAcara({token:'bad'}),/Sesi habis/);});
test('blank ULP rejected',()=>{const h=harness({session:{ulp:''}});assert.throws(()=>h.context.getDataBeritaAcara({token:'valid-token'}),/ULP/);});
test('Gardu filters preserved',()=>{const h=harness({session:{ulp:'ULP Toboali'},rows:gardu});const r=h.context.getDataBeritaAcara({token:'valid-token',ulp:'OTHER',peralatan:'Gardu',statusBA:'Proses TTD'});assert.equal(r.total,1);assert.equal(r.rows[0].idBA,'G1');});
test('Switching merge and sort preserved',()=>{const h=harness({session:{ulp:'ULP Toboali'},rows:gardu,switchingRows:switching});assert.deepEqual(h.context.getDataBeritaAcara({token:'valid-token'}).rows.map(x=>x.idBA),['S1','G1','G2']);});
test('Switching access errors rethrown',()=>{const h=harness({session:{ulp:'ULP Toboali'},rows:gardu,switchingError:'Akses ditolak'});assert.throws(()=>h.context.getDataBeritaAcara({token:'valid-token'}),/Akses ditolak/);});
test('ordinary errors preserve shape',()=>{const h=harness({session:{ulp:'ULP Toboali'},rows:gardu,switchingError:'sheet unavailable'});assert.deepEqual(h.context.getDataBeritaAcara({token:'valid-token'}),{ok:false,message:'Error Berita Acara: sheet unavailable'});});
test('BA page registers token injection',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent('valid-token','SIE-BeritaAcara');assert.match(r.html,/getDataBeritaAcara/);assert.match(r.html,/SISI_BUTUH_TOKEN/);});
