'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','SiSi_BackEnd','Core','ZZZZZZZ-BA-Master-Sync-Auth.js'),'utf8');
const TOKEN='11111111-1111-4111-8111-111111111111';
function harness({session,result}={}){const calls=[];const context={updateMasterGarduDariBA(id){calls.push(id);return result||{ok:true,action:'update',nomorGardu:'TB0001'};},getPageContent:(token,page)=>({success:true,html:'<main>',sesi:{token},page}),guard_(args,opts){const token=String(args&&args[0]||'');if(token!==TOKEN)throw new Error(token?'Sesi habis atau tidak valid.':'Sesi tidak ditemukan.');if(!session)throw new Error('Sesi habis atau tidak valid.');if(!String(session.ulp||'').trim())throw new Error('Akun belum terhubung ke ULP.');return{token,sesi:session,ulp:session.ulp,opts};}};vm.createContext(context);vm.runInContext(source,context);return{context,calls};}
test('legacy one-argument call is rejected before spreadsheet work',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.updateMasterGarduDariBA('BA-1'),/Sesi habis/);assert.equal(h.calls.length,0);});
test('missing token is rejected before side effects',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.updateMasterGarduDariBA('', 'BA-1'),/Sesi tidak/);assert.equal(h.calls.length,0);});
test('invalid session is rejected before side effects',()=>{const h=harness();assert.throws(()=>h.context.updateMasterGarduDariBA(TOKEN,'BA-1'),/Sesi habis/);assert.equal(h.calls.length,0);});
test('blank session ULP is rejected before side effects',()=>{const h=harness({session:{ulp:''}});assert.throws(()=>h.context.updateMasterGarduDariBA(TOKEN,'BA-1'),/ULP/);assert.equal(h.calls.length,0);});
test('valid request forwards only normalized idBA',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.updateMasterGarduDariBA(TOKEN,' BA-1 ');assert.equal(r.ok,true);assert.equal(r.action,'update');assert.deepEqual(h.calls,['BA-1']);});
test('blank id preserves validation shape after authentication',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.updateMasterGarduDariBA(TOKEN,' ');assert.equal(r.ok,false);assert.equal(r.message,'idBA wajib diisi.');assert.equal(h.calls.length,0);});
test('legacy result contract is preserved',()=>{const expected={ok:true,action:'skip',message:'Tanggal BA tidak lebih baru.'},h=harness({session:{ulp:'ULP Toboali'},result:expected}),r=h.context.updateMasterGarduDariBA(TOKEN,'BA-1');assert.equal(r,expected);});
test('BA page registers Master sync for token injection',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'SIE-BeritaAcara');assert.match(r.html,/updateMasterGarduDariBA/);assert.match(r.html,/SISI_BUTUH_TOKEN/);});
