'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const root=path.join(__dirname,'..','SiSi_BackEnd','Core');
const source=fs.readFileSync(path.join(root,'ZZZZZZZZZZZZZZ-BA-Photo-Upload-Auth.js'),'utf8');
const helper=fs.readFileSync(path.join(root,'ZZZZZZZZZZZZ-Stage4-Sheet-Write-Safety.js'),'utf8');
function harness(){const calls=[],rows=[];const context={uploadFotoBeritaAcara(request){calls.push({kind:'upload',request});return{ok:true};},updateFotoBeritaAcaraDetail(request){calls.push({kind:'update',request});return{ok:true};},_stage3RequireBaRow_(args,idBA,action){rows.push({idBA,action});}};vm.createContext(context);vm.runInContext(helper,context);vm.runInContext(source,context);return{context,calls,rows};}
test('photo upload checks row ownership and sanitizes filename and URL',()=>{const h=harness();const r=h.context.uploadFotoBeritaAcara({token:'t',idBA:'BA-1',fileName:'=evil.jpg',dataUrl:'data:image/jpeg;base64,AA==',meta:{url:'@url'}});assert.equal(r.ok,true);assert.deepEqual(h.rows,[{idBA:'BA-1',action:'BA_PHOTO_UPLOAD_ROW_OWNERSHIP'}]);assert.equal(h.calls[0].request.fileName,"'=evil.jpg");assert.equal(h.calls[0].request.meta.url,"'@url");assert.equal(Object.prototype.hasOwnProperty.call(h.calls[0].request,'token'),false);});
test('photo detail update checks row ownership and sanitizes nested payload',()=>{const h=harness();const r=h.context.updateFotoBeritaAcaraDetail({token:'t',idBA:'BA-2',slot:'foto',fileName:'@name.jpg',meta:{url:'=url'}});assert.equal(r.ok,true);assert.deepEqual(h.rows,[{idBA:'BA-2',action:'BA_PHOTO_UPDATE_ROW_OWNERSHIP'}]);assert.equal(h.calls[0].request.fileName,"'@name.jpg");assert.equal(h.calls[0].request.meta.url,"'=url");});
test('photo upload rejects missing idBA before writer',()=>{const h=harness();const r=h.context.uploadFotoBeritaAcara({token:'t',fileName:'x.jpg'});assert.equal(r.ok,false);assert.match(r.message,/idBA/);assert.equal(h.calls.length,0);});
