'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','SiSi_BackEnd','Core','ZZZZZ-BA-PDF-Auth.js'),'utf8');
const TOKEN='11111111-1111-4111-8111-111111111111';
function harness({session}={}){const calls=[];const context={generatePdfBaSwitching(...args){calls.push(['switching',...args]);return{ok:true,idBA:args[1]};},generatePdfBaPengoperasian(...args){calls.push(['gardu',...args]);return{ok:true,idBA:args[1]};},getPageContent:(token,page)=>({success:true,html:'<main>',sesi:{token},page}),guard_(args,opts){const token=String(args&&args[0]||'');if(token!==TOKEN)throw new Error(token?'Sesi habis atau tidak valid.':'Sesi tidak ditemukan.');if(!session)throw new Error('Sesi habis atau tidak valid.');if(!String(session.ulp||'').trim())throw new Error('Akun belum terhubung ke ULP.');return{token,sesi:session,ulp:session.ulp,opts};}};vm.createContext(context);vm.runInContext(source,context);return{context,calls};}
test('legacy one-argument Switching call is rejected before side effects',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.generatePdfBaSwitching('BA-SW-1'),/Sesi habis/);assert.equal(h.calls.length,0);});
test('missing token is rejected before Gardu side effects',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.generatePdfBaPengoperasian('', 'BA-G-1'),/Sesi tidak/);assert.equal(h.calls.length,0);});
test('blank session ULP is rejected before side effects',()=>{const h=harness({session:{ulp:''}});assert.throws(()=>h.context.generatePdfBaPengoperasian(TOKEN,'BA-G-1'),/ULP/);assert.equal(h.calls.length,0);});
test('valid Switching request forwards canonical token and id',()=>{const h=harness({session:{ulp:'ULP Toboali'}});const r=h.context.generatePdfBaSwitching(TOKEN,' BA-SW-1 ');assert.equal(r.ok,true);assert.equal(r.idBA,'BA-SW-1');assert.deepEqual(h.calls,[['switching',TOKEN,'BA-SW-1']]);});
test('valid Gardu request preserves result contract',()=>{const h=harness({session:{ulp:'ULP Toboali'}});const r=h.context.generatePdfBaPengoperasian(TOKEN,'BA-G-1');assert.equal(r.ok,true);assert.equal(r.idBA,'BA-G-1');assert.deepEqual(h.calls,[['gardu',TOKEN,'BA-G-1']]);});
test('blank id keeps legacy validation shape after authentication',()=>{const h=harness({session:{ulp:'ULP Toboali'}});const r=h.context.generatePdfBaPengoperasian(TOKEN,' ');assert.equal(r.ok,false);assert.equal(r.message,'idBA wajib diisi.');assert.equal(h.calls.length,0);});
test('BA page registers both PDF functions for token injection',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'SIE-BeritaAcara');assert.match(r.html,/generatePdfBaSwitching/);assert.match(r.html,/generatePdfBaPengoperasian/);assert.match(r.html,/SISI_BUTUH_TOKEN/);});
