'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const root=path.join(__dirname,'..','SiSi_BackEnd','Core');
const source=fs.readFileSync(path.join(root,'ZZZZZZZZ-BA-Save-Auth.js'),'utf8');
const helper=fs.readFileSync(path.join(root,'ZZZZZZZZZZZZ-Stage4-Sheet-Write-Safety.js'),'utf8');
const TOKEN='11111111-1111-4111-8111-111111111111';
function harness({session}={}){const calls=[];const context={simpanBeritaAcaraGardu(payload){calls.push(payload);return{ok:true,idBA:'BA-GRD-1',nomorBA:'BA-GRD-1'};},getPageContent:(token,page)=>({success:true,html:'<main>',sesi:{token},page}),guard_(args,opts){const payload=args&&args[0]||{},token=String(payload.token||'');if(token!==TOKEN)throw new Error(token?'Sesi habis atau tidak valid.':'Sesi tidak ditemukan.');if(!session)throw new Error('Sesi habis atau tidak valid.');if(!String(session.ulp||'').trim())throw new Error('Akun belum terhubung ke ULP.');return{token,sesi:session,ulp:session.ulp,opts};}};vm.createContext(context);vm.runInContext(helper,context);vm.runInContext(source,context);return{context,calls};}
test('anonymous BA creation is rejected before sheet work',()=>{const h=harness({session:{ulp:'ULP Toboali'}});assert.throws(()=>h.context.simpanBeritaAcaraGardu({identitas:{nomorTrafo:'TB0001'}}),/Sesi tidak/);assert.equal(h.calls.length,0);});
test('invalid session is rejected before side effects',()=>{const h=harness();assert.throws(()=>h.context.simpanBeritaAcaraGardu({token:TOKEN,identitas:{nomorTrafo:'TB0001'}}),/Sesi habis/);assert.equal(h.calls.length,0);});
test('blank session ULP is rejected before side effects',()=>{const h=harness({session:{ulp:''}});assert.throws(()=>h.context.simpanBeritaAcaraGardu({token:TOKEN,identitas:{nomorTrafo:'TB0001'}}),/ULP/);assert.equal(h.calls.length,0);});
test('valid save strips token and uses the actual Stage 4 helper for nested payloads',()=>{const payload={token:TOKEN,jenisPekerjaan:'Pengoperasian Gardu',identitas:{nomorTrafo:'TB0001',tanggalBA:'2026-09-21',alamat:'=IMPORTDATA("x")'},trafoAwal:{penyulang:'TOBOALI'},foto:{nameplateTrafoAwal:{url:'drive-url'}}},h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.simpanBeritaAcaraGardu(payload);assert.equal(r.ok,true);assert.equal(h.calls.length,1);assert.equal(h.calls[0].identitas.alamat,"'=IMPORTDATA(\"x\")");assert.equal(h.calls[0].foto.nameplateTrafoAwal.url,payload.foto.nameplateTrafoAwal.url);assert.equal(Object.prototype.hasOwnProperty.call(h.calls[0],'token'),false);});
test('BA page registers save function for token injection',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'SIE-BeritaAcara');assert.match(r.html,/simpanBeritaAcaraGardu/);assert.match(r.html,/SISI_BUTUH_TOKEN/);});
test('unrelated pages are not modified',()=>{const h=harness({session:{ulp:'ULP Toboali'}}),r=h.context.getPageContent(TOKEN,'Dashboard');assert.equal(r.html,'<main>');});
