'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const conflict = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/ZZ-T09-Master-Gardu-Conflict.js'), 'utf8');
const gateway = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/Master-Gardu-Mobile.js'), 'utf8');
const repo = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/repositories/master_gardu_repository.dart'), 'utf8');
const materializer = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/repositories/local_master_materializer.dart'), 'utf8');
const dao = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/daos/master_gardu_dao.dart'), 'utf8');
const database = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/app_database.dart'), 'utf8');
const masterTable = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/tables/master_gardu.dart'), 'utf8');
const outboxTable = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/db/tables/gardu_outbox.dart'), 'utf8');
const screen = fs.readFileSync(path.join(root, 'SiSi_Mobile/lib/screens/gardu_screen.dart'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));

assert.match(conflict, /serverRevision/);
assert.match(conflict, /MASTER_GARDU_CONFLICT/);
assert.match(conflict, /MASTER_GARDU_REVISION_REQUIRED/);
assert.match(conflict, /_t09ReadRevision_/);
assert.match(conflict, /_t09SetRevision_/);
assert.match(conflict, /withLock_\(function/);
assert.match(conflict, /encodeURIComponent/);
assert.match(conflict, /getMasterGarduMobile = function/);
assert.match(conflict, /updateMasterGarduMobile = function/);
assert.match(gateway, /serverRevision: serverRevision/);
assert.match(gateway, /tahunPhbTr/);
assert.match(repo, /serverRevision/);
assert.match(repo, /tahunPhbTr/);
assert.match(repo, /ulpScope: ulp\.isEmpty \? null : ulp/);
assert.match(repo, /serverRevision\(asli\.gardu, ulp: asli\.ulp\)/);
assert.match(materializer, /ulpScope/);
assert.match(materializer, /gantiSemua\(rows, revisions: revisions, ulpScope: scope\)/);
assert.match(dao, /WHERE ulp = \? AND gardu = \?/);
assert.match(dao, /ulpScope/);
assert.match(dao, /antrean\(\{bool includeConflict = true\}\)/);
assert.match(dao, /includeConflict/);
assert.match(database, /PRIMARY KEY \(ulp, gardu\)/);
assert.doesNotMatch(database, /CREATE TABLE \$staged AS SELECT \* FROM \$table/);
assert.match(database, /INSERT INTO \$staged\(\$columns\) SELECT \$columns FROM \$table/);
assert.match(database, /_ensureScopedGarduTables/);
assert.match(masterTable, /primaryKey => \{ulp, gardu\}/);
assert.match(outboxTable, /primaryKey => \{ulp, gardu\}/);
assert.doesNotMatch(screen, /if \(rows\.isEmpty && ulp\.isNotEmpty/);
assert.match(screen, /_repo\.cari\('', ulp: ulp, limit: 5000\)/);
assert.match(screen, /conflict/);
assert.match(screen, /perubahan Gardu konflik/);
assert.match(packageJson.scripts.test, /t09-master-gardu-conflict\.test\.cjs/);
console.log('T-09 Master Gardu conflict contract passed.');
