'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const privacy = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/ZZ-T11-Photo-Privacy.js'), 'utf8');
const watermark = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Yandal/Tek-Watermark.js'), 'utf8');
const yandalAcl = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/ZZ-T11-Yandal-Watermark-ACL.js'), 'utf8');
const temuan = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/Tek-Temuan-Code.js'), 'utf8');
const row = fs.readFileSync(path.join(root, 'SiSi_BackEnd/Core/WO-ROW-Mobile.js'), 'utf8');
const appsscript = JSON.parse(fs.readFileSync(path.join(root, 'SiSi_BackEnd/appsscript.json'), 'utf8'));
const clasp = JSON.parse(fs.readFileSync(path.join(root, 'SiSi_BackEnd/.clasp.json'), 'utf8'));
const pushOrder = appsscript.filePushOrder;
const deployOrder = clasp.filePushOrder;
const t11Index = pushOrder.indexOf('Core/ZZ-T11-Photo-Privacy.js');
const yandalAclIndex = pushOrder.indexOf('Core/ZZ-T11-Yandal-Watermark-ACL.js');
const t13Index = pushOrder.indexOf('Core/ZZ-T13-ULP-Closed.js');
const yandalSourceIndex = deployOrder.indexOf('Yandal/Tek-Yandal-Code.js');
const yandalWatermarkIndex = deployOrder.indexOf('Yandal/Tek-Watermark.js');
const yandalAclDeployIndex = deployOrder.indexOf('Core/ZZ-T11-Yandal-Watermark-ACL.js');

assert.match(privacy, /makePublic:\s*false/);
assert.match(privacy, /getFotoPrivatT11/);
assert.match(privacy, /guard_\(arguments, \{ ulp: true/);
assert.match(privacy, /barisUlpCocok_\(g, row\.ulp\)/);
assert.match(privacy, /DriveApp\.Access\.PRIVATE/);
assert.match(privacy, /apiRouter_ = function/);
assert.match(privacy, /function\s+_uploadFotoTemuan\s*\(/);
assert.match(privacy, /simpanMobileEksekusiRow = function/);
assert.match(privacy, /updateMobileEksekusiRow = function/);
assert.match(watermark, /makePublic:\s*false/);
assert.doesNotMatch(watermark, /makePublic:\s*true/);
assert.match(yandalAcl, /prosesP0Yandal/);
assert.match(yandalAcl, /prosesSwitchingYandal/);
assert.match(yandalAcl, /_h07PrivateFile_/);
assert.match(temuan, /ANYONE_WITH_LINK/);
assert.match(row, /_uploadFotoTemuan\(/);
assert.doesNotMatch(row, /setSharing\(\s*DriveApp\.Access\.ANYONE_WITH_LINK/);
assert.ok(t11Index >= 0, 'T-11 privacy overlay must be loaded');
assert.ok(yandalAclIndex >= 0, 'Yandal ACL repair overlay must be loaded');
assert.ok(t13Index >= 0, 'T-13 containment overlay must be loaded');
assert.ok(yandalAclIndex > t11Index, 'Yandal ACL repair must load after T-11 privacy');
assert.ok(yandalAclIndex > t13Index, 'Yandal ACL repair must be the final privacy boundary');
assert.ok(yandalSourceIndex >= 0, 'Yandal processor must be in clasp deploy order');
assert.ok(yandalWatermarkIndex > yandalSourceIndex, 'Yandal watermark helper must load after processor');
assert.ok(yandalAclDeployIndex > yandalWatermarkIndex, 'ACL repair must load after all Yandal sources');
console.log('T-11 private photo contract passed.');
