import 'package:drift/drift.dart';
@TableIndex(name:'idx_master_gardu_ulp',columns:{#ulp})
@TableIndex(name:'idx_master_gardu_nomor',columns:{#gardu})
class MasterGardus extends Table{
 @override String get tableName=>'master_gardu';@override Set<Column> get primaryKey=>{gardu};
 TextColumn get ulp=>text().withDefault(const Constant(''))();TextColumn get gardu=>text()();TextColumn get alamat=>text().withDefault(const Constant(''))();TextColumn get penyulang=>text().withDefault(const Constant(''))();TextColumn get section=>text().withDefault(const Constant(''))();
 TextColumn get jenisGardu=>text().withDefault(const Constant(''))();TextColumn get merk=>text().withDefault(const Constant(''))();TextColumn get kapasitasKva=>text().withDefault(const Constant(''))();TextColumn get noSeri=>text().withDefault(const Constant(''))();TextColumn get tahunTrafo=>text().withDefault(const Constant(''))();TextColumn get typeSeal=>text().withDefault(const Constant(''))();TextColumn get beratTrafo=>text().withDefault(const Constant(''))();TextColumn get volumeMinyak=>text().withDefault(const Constant(''))();
 TextColumn get merkPhbTr=>text().withDefault(const Constant(''))();TextColumn get nomorSeriPhbTr=>text().withDefault(const Constant(''))();TextColumn get tahunPhbTr=>text().withDefault(const Constant(''))();TextColumn get jamUkurWbp=>text().withDefault(const Constant(''))();TextColumn get tanggalPengukuran=>text().withDefault(const Constant(''))();TextColumn get kepemilikan=>text().withDefault(const Constant(''))();
 TextColumn get wbpRs=>text().withDefault(const Constant(''))();TextColumn get wbpSt=>text().withDefault(const Constant(''))();TextColumn get wbpTr=>text().withDefault(const Constant(''))();TextColumn get wbpRn=>text().withDefault(const Constant(''))();TextColumn get wbpSn=>text().withDefault(const Constant(''))();TextColumn get wbpTn=>text().withDefault(const Constant(''))();TextColumn get wbpR=>text().withDefault(const Constant(''))();TextColumn get wbpS=>text().withDefault(const Constant(''))();TextColumn get wbpT=>text().withDefault(const Constant(''))();TextColumn get wbpN=>text().withDefault(const Constant(''))();
 TextColumn get lwbpRs=>text().withDefault(const Constant(''))();TextColumn get lwbpSt=>text().withDefault(const Constant(''))();TextColumn get lwbpTr=>text().withDefault(const Constant(''))();TextColumn get lwbpRn=>text().withDefault(const Constant(''))();TextColumn get lwbpSn=>text().withDefault(const Constant(''))();TextColumn get lwbpTn=>text().withDefault(const Constant(''))();TextColumn get lwbpR=>text().withDefault(const Constant(''))();TextColumn get lwbpS=>text().withDefault(const Constant(''))();TextColumn get lwbpT=>text().withDefault(const Constant(''))();TextColumn get lwbpN=>text().withDefault(const Constant(''))();
 TextColumn get arusMaxPerFasa=>text().withDefault(const Constant(''))();TextColumn get pembebananKva=>text().withDefault(const Constant(''))();TextColumn get pembebananKw=>text().withDefault(const Constant(''))();TextColumn get persentaseBeban=>text().withDefault(const Constant(''))();TextColumn get kategoriBeban=>text().withDefault(const Constant(''))();
}
